OPTIMIZE TABLE TBL_SERVICE;

ALTER TABLE TBL_SERVICE 
	ADD INDEX INDX_REQUESTED_BY(REQUESTED_BY);
	
ALTER TABLE TBL_SERVICE 
	ADD INDEX INDX_REQUESTED_CELLPHONE(REQUESTED_CELLPHONE);	
	
ALTER TABLE TBL_SERVICE 
	ADD INDEX INDX_REQUESTED_EMAIL(REQUESTED_EMAIL);	
	
ALTER TABLE TBL_SERVICE 
	ADD INDEX INDX_DELIVER_TO(DELIVER_TO);
	
ALTER TABLE TBL_SERVICE 
	ADD INDEX INDX_DELIVER_CELLPHONE(DELIVER_CELLPHONE);	
	
ALTER TABLE TBL_SERVICE 
	ADD INDEX INDX_DELIVER_EMAIL(DELIVER_EMAIL);	
	
