INSERT INTO TBL_SYSTEM_RESOURCE VALUES (0,'webapi','API de integración de UBIO',2,TRUE,FALSE,NOW(),'carlcaba',NULL,NULL);

INSERT INTO TBL_SYSTEM_CONFIGURATION VALUES (0,'API_SECRET_KEY','fcvxcnfrhrtghkfghgwerikdf',2,FALSE,FALSE,100,FALSE,NOW(),'carlcaba',NULL,NULL);
