-- RESET THE SCHEMA */
DROP SCHEMA IF EXISTS VTAPPCORP;

-- CREATE THE SCHEMA */
CREATE DATABASE IF NOT EXISTS VTAPPCORP;

-- SELECTS IT */
USE VTAPPCORP;

-- CREATE USER */
GRANT USAGE ON VTAPPCORP.* TO VTAPPCORP_USER IDENTIFIED BY 'Vt4ppC0rp0r1t3$';

-- GRANT PRIVILEGES */
GRANT ALL PRIVILEGES ON VTAPPCORP.* TO VTAPPCORP_USER;


-- CREATE USER ALTERTNATE */
GRANT USAGE ON VTAPPCORP.* TO VTAPPCORP_USER_2 IDENTIFIED BY 'Vt4ppC0rp0r1t3$';

-- GRANT PRIVILEGES */
GRANT ALL PRIVILEGES ON VTAPPCORP.* TO VTAPPCORP_USER_2;


-- CREATE USER ALTERTNATE */
GRANT USAGE ON VTAPPCORP.* TO VTAPPCORP_USER_3 IDENTIFIED BY 'Vt4ppC0rp0r1t3$';

-- GRANT PRIVILEGES */
GRANT ALL PRIVILEGES ON VTAPPCORP.* TO VTAPPCORP_USER_3;



-- ******************************************
-- SYSTEM TABLES
-- ********************************************/

-- LOG TABLE */
CREATE TABLE TBL_SYSTEM_LOG (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	USER_IP VARCHAR(20) COMMENT 'true',
	USER_ID VARCHAR(50) COMMENT 'true',
	LOGDATE DATETIME COMMENT 'true',
	TEXT_TRANSACTION VARCHAR(5000) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_LOG PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the system log';

-- CONFIGURATION LOG */
CREATE TABLE TBL_SYSTEM_CONFIGURATION (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	KEY_NAME VARCHAR(100) COMMENT 'true',
	KEY_VALUE VARCHAR(2000) COMMENT 'true',
	KEY_TYPE TINYINT UNSIGNED COMMENT 'true',
	ENCRYPTED BOOLEAN DEFAULT FALSE COMMENT 'true',
	LOAD_INIT BOOLEAN DEFAULT FALSE COMMENT 'true',
	ACCESS_TO TINYINT UNSIGNED COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_CONFIGURATION PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the system configuration';

-- SYSTEM LANGUAGES */
CREATE TABLE TBL_SYSTEM_LANGUAGE (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	LANGUAGE_NAME VARCHAR(50) NOT NULL COMMENT 'true',
	ABBREVATION VARCHAR(3) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_LANGUAGE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Available languages';

-- COUNTRIES TABLE */
CREATE TABLE TBL_SYSTEM_COUNTRY (
	ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	COUNTRY VARCHAR(255) NOT NULL COMMENT 'true',
	FIPS104 VARCHAR(255) DEFAULT NULL COMMENT 'true',
	ISO2 VARCHAR(255) DEFAULT NULL COMMENT 'true',
	ISO3 VARCHAR(255) DEFAULT NULL COMMENT 'true',
	ISON VARCHAR(255) DEFAULT NULL COMMENT 'true',
	INTERNET VARCHAR(255) DEFAULT NULL COMMENT 'true',
	CAPITAL VARCHAR(255) DEFAULT NULL COMMENT 'true',
	MAPREFERENCE VARCHAR(255) DEFAULT NULL COMMENT 'true',
	NACIONALITYSINGULAR VARCHAR(255) DEFAULT NULL COMMENT 'true',
	NACIONALITYPLURAL VARCHAR(255) DEFAULT NULL COMMENT 'true',
	CURRENCY VARCHAR(255) DEFAULT NULL COMMENT 'true',
	CURRENCYCODE VARCHAR(255) DEFAULT NULL COMMENT 'true',
	POPULATION VARCHAR(255) DEFAULT NULL COMMENT 'true',
	TITLE VARCHAR(255) DEFAULT NULL COMMENT 'true',
	COMMENT VARCHAR(255) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_COUNTRY PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of countries';

-- CITIES TABLE */
CREATE TABLE TBL_SYSTEM_CITY (
	ID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	CITY_NAME VARCHAR(100) COMMENT 'true',
	COUNTRY_ID MEDIUMINT UNSIGNED COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_CITY PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of cities';

ALTER TABLE TBL_SYSTEM_CITY ADD
	CONSTRAINT FK_CITY_COUNTRY FOREIGN KEY (COUNTRY_ID)
    REFERENCES TBL_SYSTEM_COUNTRY (ID)
    ON DELETE RESTRICT;

-- ZONE TABLE */
CREATE TABLE TBL_SYSTEM_ZONE (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	PARENT_ZONE INTEGER UNSIGNED DEFAULT 0 COMMENT 'true', 
	ZONE_NAME VARCHAR(100) COMMENT 'true',
	CITY_ID MEDIUMINT UNSIGNED COMMENT 'true',
	LATITUDE_FROM VARCHAR(100) COMMENT 'true',
	LONGITUDE_FROM VARCHAR(100) COMMENT 'true',
	STREET_TYPE VARCHAR(100) COMMENT 'true',
	FROM_STREET VARCHAR(100) COMMENT 'true',
	ADDON_FROM_STREET VARCHAR(50),
	TO_STREET VARCHAR(100) COMMENT 'true',
	ADDON_TO_STREET VARCHAR(50) COMMENT 'true',
	LATITUDE_TO VARCHAR(100) COMMENT 'true',
	LONGITUDE_TO VARCHAR(100) COMMENT 'true',
	AVENUE_TYPE VARCHAR(100) COMMENT 'true',
	FROM_AVENUE VARCHAR(100) COMMENT 'true',
	ADDON_FROM_AVENUE VARCHAR(50) COMMENT 'true',
	TO_AVENUE VARCHAR(100) COMMENT 'true',
	ADDON_TO_AVENUE VARCHAR(50) COMMENT 'true',
	KML LONGTEXT COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_ZONE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of cities';

ALTER TABLE TBL_SYSTEM_ZONE ADD
	CONSTRAINT FK_ZONE_CITY FOREIGN KEY (CITY_ID)
    REFERENCES TBL_SYSTEM_CITY (ID)
    ON DELETE RESTRICT;

-- SYSTEM RESOURCES */
CREATE TABLE TBL_SYSTEM_RESOURCE (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	RESOURCE_TEXT VARCHAR(4000) NOT NULL COMMENT 'true',
	LANGUAGE_ID SMALLINT UNSIGNED NOT NULL COMMENT 'true',
	IS_SYSTEM BOOLEAN DEFAULT FALSE COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_RESOURCE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Resources system messages ';

ALTER TABLE TBL_SYSTEM_RESOURCE ADD
    CONSTRAINT FK_RESOURCE_LANGUAGE FOREIGN KEY (LANGUAGE_ID)
    REFERENCES TBL_SYSTEM_LANGUAGE (ID)
    ON DELETE RESTRICT;

CREATE INDEX INDX_RESOURCE ON TBL_SYSTEM_RESOURCE (RESOURCE_NAME) USING BTREE;

-- ACCESS TABLE */
CREATE TABLE TBL_SYSTEM_ACCESS (
	ID TINYINT UNSIGNED NOT NULL COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	PREFIX VARCHAR(10) COMMENT 'true',
	LINK_TO VARCHAR(100) COMMENT 'true',
	APP_TITLE VARCHAR(100) COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_ACCESS PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of access';
ALTER TABLE TBL_SYSTEM_ACCESS ADD
    CONSTRAINT FK_ACCESS_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;

-- MENU TABLE */
CREATE TABLE TBL_SYSTEM_MENU (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	LINK VARCHAR(200) NOT NULL COMMENT 'true',
	ICON VARCHAR(50) NOT NULL COMMENT 'true',
	ACCESS_ID TINYINT UNSIGNED NOT NULL COMMENT 'true',
	PARENT_ID SMALLINT UNSIGNED NOT NULL COMMENT 'true',
	ORDER_ID SMALLINT UNSIGNED NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_MENU PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the menu';

ALTER TABLE TBL_SYSTEM_MENU ADD
    CONSTRAINT FK_MENU_ACCESS FOREIGN KEY (ACCESS_ID)
    REFERENCES TBL_SYSTEM_ACCESS (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SYSTEM_MENU ADD
    CONSTRAINT FK_MENU_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;

-- SYSTEM DOCUMENT TYPE TABLE */
CREATE TABLE TBL_SYSTEM_DOCUMENT_TYPE (
	ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	ABBREVIATION VARCHAR(5) COMMENT 'true',
	REGEX VARCHAR(100) COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_DOCUMENT_TYPE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of document type';
ALTER TABLE TBL_SYSTEM_DOCUMENT_TYPE ADD
    CONSTRAINT FK_DOCUMENT_TYPE_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;


-- SYSTEM VEHICLE TYPE TABLE */
CREATE TABLE TBL_SYSTEM_VEHICLE_TYPE (
	ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	PROTECTION BOOLEAN DEFAULT FALSE COMMENT 'true',
	ICON VARCHAR(100) COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_VEHICLE_TYPE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of vehicle types';
ALTER TABLE TBL_SYSTEM_VEHICLE_TYPE ADD
    CONSTRAINT FK_VEHICLE_TYPE_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;


-- SYSTEM VEHICLE PROTECTION TABLE */
CREATE TABLE TBL_SYSTEM_VEHICLE_PROTECTION (
	ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	VEHICLE_TYPE_ID TINYINT UNSIGNED NOT NULL COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_VEHICLE_PROTECTION PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of vehicle protection';
ALTER TABLE TBL_SYSTEM_VEHICLE_PROTECTION ADD
    CONSTRAINT FK_VEHICLE_PROTECTION_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SYSTEM_VEHICLE_PROTECTION ADD
    CONSTRAINT FK_VEHICLE_PROTECTION_TYPE FOREIGN KEY (VEHICLE_TYPE_ID)
    REFERENCES TBL_SYSTEM_VEHICLE_TYPE (ID)
    ON DELETE RESTRICT;
	



-- SYSTEM CLIENT TYPE TABLE */
CREATE TABLE TBL_SYSTEM_CLIENT_TYPE (
	ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_CLIENT_TYPE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of client types';
ALTER TABLE TBL_SYSTEM_CLIENT_TYPE ADD
    CONSTRAINT FK_CLIENT_TYPE_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;


-- SYSTEM PAYMENT TYPE TABLE */
CREATE TABLE TBL_SYSTEM_PAYMENT_TYPE (
	ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	CLIENT_TYPE_ID TINYINT UNSIGNED NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_PAYMENT_TYPE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of payment types';
ALTER TABLE TBL_SYSTEM_PAYMENT_TYPE ADD
    CONSTRAINT FK_PAYMENT_TYPE_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SYSTEM_PAYMENT_TYPE ADD
    CONSTRAINT FK_PAYMENT_TYPE_CLIENT_TYPE FOREIGN KEY (CLIENT_TYPE_ID)
    REFERENCES TBL_SYSTEM_CLIENT_TYPE (ID)
    ON DELETE RESTRICT;


-- SYSTEM USER TABLE */
CREATE TABLE TBL_SYSTEM_USER (
	ID VARCHAR(100) NOT NULL COMMENT 'true',
	THE_PASSWORD VARCHAR(150) NOT NULL COMMENT 'true',
	FIRST_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	LAST_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	IDENTIFICATION VARCHAR(100) NOT NULL COMMENT 'true',
	EMAIL VARCHAR(150) NOT NULL COMMENT 'true',
	ADDRESS VARCHAR(200) NOT NULL COMMENT 'true',
	PHONE VARCHAR(100) COMMENT 'true',
	CELLPHONE VARCHAR(100) NOT NULL COMMENT 'true',
	CITY_ID MEDIUMINT UNSIGNED COMMENT 'true',
	LATITUDE VARCHAR(100) COMMENT 'true',
	LONGITUDE VARCHAR(100) COMMENT 'true',
	FACEBOOK_USER VARCHAR(100) COMMENT 'true',
	GOOGLE_USER VARCHAR(100) COMMENT 'true',
	ACCESS_ID TINYINT UNSIGNED COMMENT 'true',
	REFERENCE VARCHAR(100) COMMENT 'true',
	CHANGE_PASSWORD BOOLEAN DEFAULT TRUE COMMENT 'true',
	ON_LINE BOOLEAN DEFAULT FALSE COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_USER PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Registered system Users';

ALTER TABLE TBL_SYSTEM_USER ADD
    CONSTRAINT FK_SYSTEM_USER_ACCESS FOREIGN KEY (ACCESS_ID)
    REFERENCES TBL_SYSTEM_ACCESS (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SYSTEM_USER ADD
    CONSTRAINT FK_SYSTEM_USER_CITY FOREIGN KEY (CITY_ID)
    REFERENCES TBL_SYSTEM_CITY (ID)
    ON DELETE RESTRICT;	
		
-- NOTIFICATION TYPE TABLE */
CREATE TABLE TBL_SYSTEM_NOTIFICATION_TYPE (
	ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	TEXT_TYPE VARCHAR(50) NOT NULL COMMENT 'true',
	ICON VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_NOTIFICATION_TYPE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the notification type description';
ALTER TABLE TBL_SYSTEM_NOTIFICATION_TYPE ADD
    CONSTRAINT FK_NOTIFICATION_TYPE_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;


-- SYSTEM NOTIFICATIONS */
CREATE TABLE TBL_SYSTEM_NOTIFICATION (
    ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
    USER_ID VARCHAR(100) NOT NULL COMMENT 'true',
    TYPE_ID TINYINT UNSIGNED NOT NULL COMMENT 'true',
    MESSAGE VARCHAR(4000) NOT NULL COMMENT 'true',
    SOURCE VARCHAR(4000) NOT NULL COMMENT 'true',
    VIEWED_ON DATETIME COMMENT 'true',
    IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
    REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
    REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
  	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
    CONSTRAINT PK_SYSTEM_NOTIFICATION PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'System notifications to users';

ALTER TABLE TBL_SYSTEM_NOTIFICATION ADD
    CONSTRAINT FK_NOTIFICATION_TYPE FOREIGN KEY (TYPE_ID)
    REFERENCES TBL_SYSTEM_NOTIFICATION_TYPE (ID)
    ON DELETE RESTRICT;
	
-- SYSTEM TRACE */
CREATE TABLE TBL_SYSTEM_TRACE (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	LOG_ID INTEGER UNSIGNED NOT NULL COMMENT 'true',
	TABLE_ORIGIN VARCHAR(100) NOT NULL COMMENT 'true',
	RECORD_ID VARCHAR(50) NOT NULL COMMENT 'true',
	OLD_RECORD VARCHAR(4000) NOT NULL COMMENT 'true',
	NEW_RECORD VARCHAR(4000) NOT NULL COMMENT 'true',
    CONSTRAINT PK_SYSTEM_TRACE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'System Trace for Update records';

ALTER TABLE TBL_SYSTEM_TRACE ADD
    CONSTRAINT FK_SYSTEM_TRACE_LOG FOREIGN KEY (LOG_ID)
    REFERENCES TBL_SYSTEM_LOG (ID)
    ON DELETE RESTRICT;


-- RATES
CREATE TABLE TBL_SYSTEM_RATE (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	DISTANCE_INITIAL FLOAT(15,2) NOT NULL DEFAULT 0 COMMENT 'true',
	DISTANCE_FINAL FLOAT(15,2) NOT NULL DEFAULT 0 COMMENT 'true',
	RATE FLOAT(15,2) NOT NULL DEFAULT 0 COMMENT 'true',
	FLASH FLOAT(15,2) NOT NULL DEFAULT 0 COMMENT 'true',
	ROUND_TRIP FLOAT(15,2) NOT NULL DEFAULT 0 COMMENT 'true',
	FINAL_ROUND_TRIP FLOAT(15,2) NOT NULL DEFAULT 0 COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_RATE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the rates for distance in meters';
	

-- CLIENT TYPE
CREATE TABLE TBL_SYSTEM_CLIENT_PAYMENT_TYPE (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_CLIENT_PAYMENT_TYPE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the client\'s payment type';
ALTER TABLE TBL_SYSTEM_CLIENT_PAYMENT_TYPE ADD
    CONSTRAINT FK_CLIENT_PAYMENT_TYPE_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;







/*******************************************
APPLICATION TABLES
********************************************/

-- PARTNER TABLE */
CREATE TABLE TBL_PARTNER (
	ID VARCHAR(50) NOT NULL COMMENT 'true',
	PARTNER_NAME VARCHAR(200) NOT NULL COMMENT 'true',
	IDENTIFICATION VARCHAR(100) NOT NULL COMMENT 'true',
	ADDRESS VARCHAR(200) NOT NULL COMMENT 'true',
	PHONE VARCHAR(100) COMMENT 'true',
	PHONE_ALT VARCHAR(100) COMMENT 'true',
	CELLPHONE VARCHAR(100) NOT NULL COMMENT 'true',
	CELLPHONE_ALT VARCHAR(100) COMMENT 'true',
	CITY_ID MEDIUMINT UNSIGNED COMMENT 'true',
	LATITUDE VARCHAR(100) COMMENT 'true',
	LONGITUDE VARCHAR(100) COMMENT 'true',
	EMAIL VARCHAR(100) NOT NULL COMMENT 'true',
	EMAIL_ALT VARCHAR(100) COMMENT 'true',
	CONTACT_NAME VARCHAR(200) NOT NULL COMMENT 'true',
	EMAIL_CONTACT VARCHAR(100) NOT NULL COMMENT 'true',
	PHONE_CONTACT VARCHAR(100) NOT NULL COMMENT 'true',
	CELLPHONE_CONTACT VARCHAR(100) NOT NULL COMMENT 'true',
	SKIN VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_PARTNER PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the messenger partners';
ALTER TABLE TBL_PARTNER ADD
    CONSTRAINT FK_PARTNER_CITY FOREIGN KEY (CITY_ID)
    REFERENCES TBL_SYSTEM_CITY (ID)
    ON DELETE RESTRICT;

-- AREA TABLE */
CREATE TABLE TBL_AREA (
	ID VARCHAR(50) NOT NULL COMMENT 'true',
	AREA_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	TITLE VARCHAR(10) NOT NULL COMMENT 'true',
	COSTCENTER VARCHAR(50) COMMENT 'true',
	CLIENT_ID VARCHAR(50) NOT NULL COMMENT 'true',
	AREA_TYPE_ID SMALLINT UNSIGNED NOT NULL COMMENT 'true',
	PARTNER BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_AREA PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the area description';


-- POSITION TABLE */
CREATE TABLE TBL_POSITION (
	ID VARCHAR(50) NOT NULL COMMENT 'true',
	POSITION_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	TITLE VARCHAR(10) NOT NULL COMMENT 'true',
	AREA_ID VARCHAR(50) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_POSITION PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the position description';
ALTER TABLE TBL_POSITION ADD
    CONSTRAINT FK_POSITION_AREA FOREIGN KEY (AREA_ID)
    REFERENCES TBL_AREA (ID)
    ON DELETE RESTRICT;

-- PARTNER'S EMPLOYEE TABLE */
CREATE TABLE TBL_EMPLOYEE (
    ID VARCHAR(50) NOT NULL  COMMENT 'true',
    PARTNER_ID VARCHAR(50) NOT NULL COMMENT 'true',
	AREA_ID VARCHAR(50) COMMENT 'true',
    USER_ID VARCHAR(50) NOT NULL COMMENT 'true',
	ACCESS_ID  TINYINT UNSIGNED COMMENT 'true',
	FIRST_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	MIDDLE_NAME VARCHAR(100) COMMENT 'true',
	LAST_NAME VARCHAR(200) NOT NULL COMMENT 'true',
	IDENTIFICATION VARCHAR(100) NOT NULL COMMENT 'true',
	ADDRESS VARCHAR(200) NOT NULL COMMENT 'true',
	PHONE VARCHAR(100) COMMENT 'true',
	CELLPHONE VARCHAR(100) NOT NULL COMMENT 'true',
	CITY_ID MEDIUMINT UNSIGNED COMMENT 'true',
	LATITUDE VARCHAR(100) COMMENT 'true',
	LONGITUDE VARCHAR(100) COMMENT 'true',
	EMAIL VARCHAR(100) NOT NULL COMMENT 'true',
	LAST_CONNECTION DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'true',
    RECORDS BOOLEAN DEFAULT FALSE COMMENT 'true',
	IMEI BOOLEAN DEFAULT FALSE COMMENT 'true',
	PENALTIES BOOLEAN DEFAULT FALSE COMMENT 'true',
    IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
    REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
    REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of partners employees';
ALTER TABLE TBL_EMPLOYEE ADD
    CONSTRAINT FK_EMPLOYEE_PARTNER FOREIGN KEY (PARTNER_ID)
    REFERENCES TBL_PARTNER (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_EMPLOYEE ADD
	CONSTRAINT FK_EMPLOYEE_AREA FOREIGN KEY (AREA_ID)
	REFERENCES TBL_AREA (ID)
	ON DELETE RESTRICT;
ALTER TABLE TBL_EMPLOYEE ADD
	CONSTRAINT FK_EMPLOYEE_USER FOREIGN KEY (USER_ID)
	REFERENCES TBL_SYSTEM_USER (ID)
	ON DELETE RESTRICT;
ALTER TABLE TBL_EMPLOYEE ADD
    CONSTRAINT FK_EMPLOYEE_CITY FOREIGN KEY (CITY_ID)
    REFERENCES TBL_SYSTEM_CITY (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_EMPLOYEE ADD
    CONSTRAINT FK_EMPLOYEE_ACCESS FOREIGN KEY (ACCESS_ID)
    REFERENCES TBL_SYSTEM_ACCESS (ID)
    ON DELETE RESTRICT;
	
	
-- JOURNEY TABLE */
CREATE TABLE TBL_JOURNEY (
	ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_JOURNEY PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents journey description';
ALTER TABLE TBL_JOURNEY ADD
    CONSTRAINT FK_JOURNEY_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;
	
	
-- VEHICLE TABLE */
CREATE TABLE TBL_VEHICLE (
    ID VARCHAR(50) NOT NULL COMMENT 'true',
    EMPLOYEE_ID VARCHAR(50) NOT NULL COMMENT 'true',
    VEHICLE_TYPE_ID TINYINT UNSIGNED COMMENT 'true',
	PLATE VARCHAR(10) NOT NULL COMMENT 'true',
    BRAND VARCHAR(100) COMMENT 'true',
    MODEL VARCHAR(100) COMMENT 'true',
    YEAR SMALLINT UNSIGNED COMMENT 'true',
	SERIAL_NUMBER VARCHAR(150) NOT NULL COMMENT 'true',
	INSURANCE_NUMBER VARCHAR(100) NOT NULL COMMENT 'true',
	INSURANCE_COMPANY VARCHAR(100) NOT NULL COMMENT 'true',
	EXPIRATION_DATE DATETIME NOT NULL COMMENT 'true',
	LICENCE_NUMBER VARCHAR(100) NOT NULL COMMENT 'true',
	LICENCE_EXPIRATION DATETIME NOT NULL COMMENT 'true',
	LICENCE_CATEGORY_ID VARCHAR(5) NOT NULL COMMENT 'true',
	TECHNICAL_REVISION BOOLEAN DEFAULT FALSE COMMENT 'true',
	TECHNICAL_REVISION_EXPIRATION DATETIME COMMENT 'true',
	JOURNEY_ID TINYINT UNSIGNED COMMENT 'true',
	EXPERIENCE_YEARS SMALLINT UNSIGNED NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
    REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
    REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_VEHICLE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of employees vehicles';
ALTER TABLE TBL_VEHICLE ADD
    CONSTRAINT FK_VEHICLE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
    REFERENCES TBL_EMPLOYEE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_VEHICLE ADD
    CONSTRAINT FK_VEHICLE_TYPE FOREIGN KEY (VEHICLE_TYPE_ID)
    REFERENCES TBL_SYSTEM_VEHICLE_TYPE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_VEHICLE ADD
    CONSTRAINT FK_VEHICLE_JOURNEY FOREIGN KEY (JOURNEY_ID)
    REFERENCES TBL_JOURNEY (ID)
    ON DELETE RESTRICT;


-- SERVICE STATE TABLE */
CREATE TABLE TBL_SERVICE_STATE (
	ID VARCHAR(50) NOT NULL COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	ICON VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_SERVICE_STATE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the service state description';
ALTER TABLE TBL_SERVICE_STATE ADD
    CONSTRAINT FK_SERVICE_STATE_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;


-- DELIVER TYPE TABLE */
CREATE TABLE TBL_DELIVERY_TYPE (
	ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_DELIVERY_TYPE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the delivery types description';
ALTER TABLE TBL_DELIVERY_TYPE ADD
    CONSTRAINT FK_DELIVERY_TYPE_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;


-- CLIENT TABLE */
CREATE TABLE TBL_CLIENT (
	ID VARCHAR(50) NOT NULL COMMENT 'true',
	CLIENT_NAME VARCHAR(200) NOT NULL COMMENT 'true',
	PAYMENT_TYPE_ID TINYINT UNSIGNED NOT NULL COMMENT 'true',
	CLIENT_PAYMENT_TYPE_ID SMALLINT UNSIGNED NOT NULL DEFAULT 4 COMMENT 'true',
	IDENTIFICATION VARCHAR(100) NOT NULL COMMENT 'true',
	ADDRESS VARCHAR(200) NOT NULL COMMENT 'true',
	PHONE VARCHAR(100) COMMENT 'true',
	PHONE_ALT VARCHAR(100) COMMENT 'true',
	CELLPHONE VARCHAR(100) NOT NULL COMMENT 'true',
	CELLPHONE_ALT VARCHAR(100) COMMENT 'true',
	CITY_ID MEDIUMINT UNSIGNED COMMENT 'true',
	LATITUDE VARCHAR(100) COMMENT 'true',
	LONGITUDE VARCHAR(100) COMMENT 'true',
	EMAIL VARCHAR(100) NOT NULL COMMENT 'true',
	EMAIL_ALT VARCHAR(100) COMMENT 'true',
	CONTACT_NAME VARCHAR(200) NOT NULL COMMENT 'true',
	EMAIL_CONTACT VARCHAR(100) NOT NULL COMMENT 'true',
	PHONE_CONTACT VARCHAR(100) NOT NULL COMMENT 'true',
	CELLPHONE_CONTACT VARCHAR(100) NOT NULL COMMENT 'true',
	EXPIRES_ON DATETIME COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_CLIENT PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the clients';
ALTER TABLE TBL_CLIENT ADD
    CONSTRAINT FK_CLIENT_CITY FOREIGN KEY (CITY_ID)
    REFERENCES TBL_SYSTEM_CITY (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_CLIENT ADD
    CONSTRAINT FK_CLIENT_PAYMENT_TYPE FOREIGN KEY (PAYMENT_TYPE_ID)
    REFERENCES TBL_SYSTEM_PAYMENT_TYPE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_AREA ADD
    CONSTRAINT FK_AREA_CLIENT FOREIGN KEY (CLIENT_ID)
    REFERENCES TBL_CLIENT (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_CLIENT ADD
    CONSTRAINT FK_CLIENT_CLIENT_PAYMENT_TYPE_ FOREIGN KEY (CLIENT_PAYMENT_TYPE_ID)
    REFERENCES TBL_SYSTEM_CLIENT_PAYMENT_TYPE (ID)
    ON DELETE RESTRICT;

	

-- SERVICE TABLE */
CREATE TABLE TBL_SERVICE (
    ID VARCHAR(50) NOT NULL COMMENT 'true',
	USER_ID VARCHAR(50) NOT NULL COMMENT 'true',
	CLIENT_ID VARCHAR(50) NOT NULL COMMENT 'true',
	REQUESTED_BY VARCHAR(200) NOT NULL COMMENT 'true',
	REQUESTED_EMAIL VARCHAR(200) NOT NULL COMMENT 'true',
	REQUESTED_PHONE VARCHAR(200) NOT NULL COMMENT 'true',
	REQUESTED_CELLPHONE VARCHAR(200) NOT NULL COMMENT 'true',
	REQUESTED_IP VARCHAR(20) NOT NULL COMMENT 'true',
	REQUESTED_ADDRESS VARCHAR(500) NOT NULL COMMENT 'true',
	REQUESTED_ZONE INTEGER UNSIGNED NOT NULL COMMENT 'true',
	DELIVER_DESCRIPTION VARCHAR(5000) NOT NULL COMMENT 'true',
	OBSERVATION VARCHAR(5000) NOT NULL COMMENT 'true',
	DELIVER_TO VARCHAR(200) NOT NULL COMMENT 'true',
	DELIVER_EMAIL VARCHAR(200) COMMENT 'true',
	DELIVER_PHONE VARCHAR(200) NOT NULL COMMENT 'true',
	DELIVER_CELLPHONE VARCHAR(200) NOT NULL COMMENT 'true',
	DELIVER_ADDRESS VARCHAR(500) NOT NULL COMMENT 'true',
	DELIVER_ZONE INTEGER UNSIGNED NOT NULL COMMENT 'true',
	DELIVERY_TYPE TINYINT UNSIGNED NOT NULL COMMENT 'true',
	QUANTITY SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'true',
	PRICE FLOAT(15,8) NOT NULL COMMENT 'true',
	STATE_ID VARCHAR(50) NOT NULL COMMENT 'true',
	VEHICLE_TYPE_ID TINYINT UNSIGNED COMMENT 'true',
    ROUND_TRIP BOOLEAN DEFAULT FALSE COMMENT 'true',
    FRAGILE BOOLEAN DEFAULT FALSE COMMENT 'true',
	INSURANCE BOOLEAN DEFAULT FALSE COMMENT 'true',
	TIME_START_TO_DELIVER TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'true',
	TIME_FINISH_TO_DELIVER TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'true',
	TOTAL_WIDTH FLOAT(15,8) NOT NULL COMMENT 'true',
	TOTAL_HEIGHT FLOAT(15,8) NOT NULL COMMENT 'true',
	TOTAL_LENGTH FLOAT(15,8) NOT NULL COMMENT 'true',
	TOTAL_WEIGHT FLOAT(15,8) NOT NULL COMMENT 'true',
    IS_BLOCKED BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'true',
    REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
    REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_SERVICE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the list of services';
/*
ALTER TABLE TBL_SERVICE ADD
	CONSTRAINT FK_SERVICE_USER FOREIGN KEY (USER_ID)
	REFERENCES TBL_SYSTEM_USER (ID)
	ON DELETE RESTRICT;
*/
ALTER TABLE TBL_SERVICE ADD
	CONSTRAINT FK_SERVICE_CLIENT FOREIGN KEY (CLIENT_ID)
    REFERENCES TBL_CLIENT (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SERVICE ADD
	CONSTRAINT FK_SERVICE_ZONE_REQUEST FOREIGN KEY (REQUESTED_ZONE)
    REFERENCES TBL_SYSTEM_ZONE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SERVICE ADD
	CONSTRAINT FK_SERVICE_ZONE_DELIVER FOREIGN KEY (DELIVER_ZONE)
    REFERENCES TBL_SYSTEM_ZONE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SERVICE ADD
	CONSTRAINT FK_SERVICE_STATE FOREIGN KEY (STATE_ID)
    REFERENCES TBL_SERVICE_STATE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SERVICE ADD
	CONSTRAINT FK_SERVICE_DELIVERY_TYPE FOREIGN KEY (DELIVERY_TYPE)
    REFERENCES TBL_DELIVERY_TYPE (ID)
    ON DELETE RESTRICT;

-- SERVICE LOG TABLE */
CREATE TABLE TBL_SERVICE_LOG (
	ID VARCHAR(50) NOT NULL COMMENT 'true',
	SERVICE_ID VARCHAR(50) NOT NULL COMMENT 'true',
	STATE_INITIAL_ID VARCHAR(50) NOT NULL COMMENT 'true',
	STATE_FINAL_ID VARCHAR(50) NOT NULL COMMENT 'true',
	EMPLOYEE_INITIAL_ID VARCHAR(50) COMMENT 'true',
	EMPLOYEE_FINAL_ID VARCHAR(50) COMMENT 'true',
	VEHICLE_INITIAL_ID VARCHAR(50) COMMENT 'true',
	VEHICLE_FINAL_ID VARCHAR(50) COMMENT 'true',
	LAST_POSITION VARCHAR(200) COMMENT 'true',
	OBSERVATION VARCHAR(5000) COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_SERVICE_LOG PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the movements for a service';

ALTER TABLE TBL_SERVICE_LOG ADD
    CONSTRAINT FK_SERVICE_LOG_SERVICE FOREIGN KEY (SERVICE_ID)
    REFERENCES TBL_SERVICE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SERVICE_LOG ADD
    CONSTRAINT FK_SERVICE_LOG_STATE_INITIAL FOREIGN KEY (STATE_INITIAL_ID)
    REFERENCES TBL_SERVICE_STATE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SERVICE_LOG ADD
    CONSTRAINT FK_SERVICE_LOG_STATE_FINAL FOREIGN KEY (STATE_FINAL_ID)
    REFERENCES TBL_SERVICE_STATE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SERVICE_LOG ADD
    CONSTRAINT FK_SERVICE_LOG_EMPLOYEE_INITIAL FOREIGN KEY (EMPLOYEE_INITIAL_ID)
    REFERENCES TBL_EMPLOYEE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SERVICE_LOG ADD
    CONSTRAINT FK_SERVICE_LOG_EMPLOYEE_FINAL FOREIGN KEY (EMPLOYEE_FINAL_ID)
    REFERENCES TBL_EMPLOYEE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SERVICE_LOG ADD
    CONSTRAINT FK_SERVICE_LOG_VEHICLE_INITIAL FOREIGN KEY (VEHICLE_INITIAL_ID)
    REFERENCES TBL_VEHICLE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_SERVICE_LOG ADD
    CONSTRAINT FK_SERVICE_LOG_VEHICLE_FINAL FOREIGN KEY (VEHICLE_FINAL_ID)
    REFERENCES TBL_VEHICLE (ID)
    ON DELETE RESTRICT;
	
-- PAYMENT TYPE TABLE */
CREATE TABLE TBL_PAYMENT_TYPE (
	ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	PAYMENT_TYPE VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_PAYMENT_TYPE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the payment types description';

-- PAYMENT STATE TABLE */
CREATE TABLE TBL_PAYMENT_STATE (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_PAYMENT_STATE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the payment states description';
ALTER TABLE TBL_PAYMENT_STATE ADD
    CONSTRAINT FK_PAYMENT_STATE_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;


-- PAYMENT TABLE */
CREATE TABLE TBL_PAYMENT (
	ID VARCHAR(50) NOT NULL COMMENT 'true',
	CLIENT_ID VARCHAR(50) NOT NULL COMMENT 'true',
	REFERENCE_ID VARCHAR(50) NOT NULL COMMENT 'true',
	PAYMENT_TYPE_ID TINYINT UNSIGNED NOT NULL COMMENT 'true',
	PAYMENT_STATE_ID SMALLINT UNSIGNED NOT NULL COMMENT 'true',
	TRANSACTION_ID VARCHAR(100),
	GATEWAY VARCHAR(100) NOT NULL COMMENT 'true',
	URL_GATEWAY VARCHAR(200) NOT NULL COMMENT 'true',
	IP_CLIENT VARCHAR(100) COMMENT 'true',
	RISK VARCHAR(100) COMMENT 'true',
	RESPONSE VARCHAR(200) COMMENT 'true',
	RESPONSE_TRACE VARCHAR(5000) COMMENT 'true',
	PAYMENT_METHOD VARCHAR(100) COMMENT 'true',
	PAYMENT_METHOD_TYPE VARCHAR(100) COMMENT 'true',
	PAYMENT_REQUESTED FLOAT(15,8) DEFAULT 0 NOT NULL COMMENT 'true',
	PAYMENT_VALUE FLOAT(15,8) DEFAULT 0 NOT NULL COMMENT 'true',
	PAYMENT_TAX_PERCENT FLOAT(15,8) DEFAULT 0 NOT NULL COMMENT 'true',
	PAYMENT_TAX FLOAT(15,8) DEFAULT 0 NOT NULL COMMENT 'true',
	PAYMENT_VALUE_ADD FLOAT(15,8) DEFAULT 0 NOT NULL COMMENT 'true',
	AUTHORIZATION_CODE VARCHAR(100) COMMENT 'true',
	AUTHORIZATION_ADDITIONAL_CODE VARCHAR(100) COMMENT 'true',
	PAYMENT_ENTITY VARCHAR(100) COMMENT 'true',
	PAYER_EMAIL VARCHAR(100) COMMENT 'true',
	PAYER_NAME VARCHAR(100) COMMENT 'true',
	PAYER_IDENTIFICATION VARCHAR(100) COMMENT 'true',
	PAYER_PHONE VARCHAR(100) COMMENT 'true',
	OBSERVATION VARCHAR(5000) COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_PAYMENT PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the payments description';
ALTER TABLE TBL_PAYMENT ADD
    CONSTRAINT FK_PAYMENT_CLIENT FOREIGN KEY (CLIENT_ID)
    REFERENCES TBL_CLIENT (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_PAYMENT ADD
    CONSTRAINT FK_PAYMENT_TYPE FOREIGN KEY (PAYMENT_TYPE_ID)
    REFERENCES TBL_PAYMENT_TYPE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_PAYMENT ADD
    CONSTRAINT FK_PAYMENT_STATE FOREIGN KEY (PAYMENT_STATE_ID)
    REFERENCES TBL_PAYMENT_STATE (ID)
    ON DELETE RESTRICT;	


-- DIRECT CHAT */
CREATE TABLE TBL_DIRECT_CHAT (
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	SENDER VARCHAR(50) NOT NULL,
	IP_SENDER VARCHAR(20) NOT NULL,
	DESTINY VARCHAR(50) NOT NULL,
	IP_READER VARCHAR(20),
	MESSAGE VARCHAR(4000),
	PRIORITY BOOLEAN DEFAULT FALSE,
	DELIVERED BOOLEAN DEFAULT FALSE,
	DELIVERED_ON DATETIME,
	READED BOOLEAN DEFAULT FALSE,
	READED_ON DATETIME,
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	REGISTERED_BY VARCHAR(50) NOT NULL,
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP,
	MODIFIED_BY VARCHAR(50),
	CONSTRAINT PK_DIRECT_CHAT PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Direct chat';

-- QUOTA TYPE TABLE
CREATE TABLE TBL_QUOTA_TYPE (
	ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	AMOUNT FLOAT(18,3) NOT NULL DEFAULT 0 COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_QUOTA_TYPE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the quota type description';
ALTER TABLE TBL_QUOTA_TYPE ADD
    CONSTRAINT FK_QUOTA_TYPE_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;
	
-- QUOTA
CREATE TABLE TBL_QUOTA (
	ID VARCHAR(50) NOT NULL COMMENT 'true',
	QUOTA_TYPE_ID TINYINT UNSIGNED NOT NULL COMMENT 'true',
	CLIENT_ID VARCHAR(50) NOT NULL COMMENT 'true',
	AMOUNT FLOAT(18,3) NOT NULL DEFAULT 0 COMMENT 'true',
	USED FLOAT(18,3) NOT NULL DEFAULT 0 COMMENT 'true',
	CREDIT_CARD_NUMBER VARCHAR(50) NOT NULL COMMENT 'true',
	CREDIT_CARD_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	DATE_EXPIRATION VARCHAR(10) NOT NULL COMMENT 'true',
	VERIFICATION_CODE VARCHAR(10) NOT NULL COMMENT 'true',
	DIFERRED_TO TINYINT UNSIGNED NOT NULL COMMENT 'true',
	PAYMENT_ID VARCHAR(50) COMMENT 'true', 
	IS_PAYED BOOLEAN DEFAULT FALSE COMMENT 'true',
	IS_VERIFIED BOOLEAN DEFAULT FALSE COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_QUOTA PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the quota type description';
ALTER TABLE TBL_QUOTA ADD
    CONSTRAINT FK_QUOTA_QUOTA_TYPE FOREIGN KEY (QUOTA_TYPE_ID)
    REFERENCES TBL_QUOTA_TYPE (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_QUOTA ADD
    CONSTRAINT FK_QUOTA_CLIENT FOREIGN KEY (CLIENT_ID)
    REFERENCES TBL_CLIENT (ID)
    ON DELETE RESTRICT;


-- EXTERNAL SESSIONS
CREATE TABLE TBL_EXTERNAL_SESSION (
	ID VARCHAR(50) NOT NULL COMMENT 'true',
	USER_ID VARCHAR(50) NOT NULL COMMENT 'true',
	ACCESS_ID TINYINT UNSIGNED NOT NULL COMMENT 'true',
	CLIENT_ID VARCHAR(50) COMMENT 'true',
	PARTNER_ID VARCHAR(50) COMMENT 'true',
	REQUESTED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_EXTERNAL_SESSION PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the external sessions';
ALTER TABLE TBL_EXTERNAL_SESSION ADD
    CONSTRAINT FK_EXTERNAL_SESSION_ACCESS FOREIGN KEY (ACCESS_ID)
    REFERENCES TBL_SYSTEM_ACCESS (ID)
    ON DELETE RESTRICT;
	
	
-- QUOTA EMPLOYEES
CREATE TABLE TBL_QUOTA_EMPLOYEE (
	ID VARCHAR(50) NOT NULL COMMENT 'true',
	CLIENT_ID VARCHAR(50) NOT NULL COMMENT 'true',
	AREA_ID VARCHAR(50) COMMENT 'true',
	USER_ID VARCHAR(50) COMMENT 'true',
	QUOTA_ID VARCHAR(50) NOT NULL COMMENT 'true',
	AMOUNT FLOAT(18,3) NOT NULL DEFAULT 0 COMMENT 'true',
	USED FLOAT(18,3) NOT NULL DEFAULT 0 COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_QUOTA_CLIENT PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the quota of an employee';
ALTER TABLE TBL_QUOTA_EMPLOYEE ADD
    CONSTRAINT FK_QUOTA_EMPLOYEE_QUOTA FOREIGN KEY (QUOTA_ID)
    REFERENCES TBL_QUOTA (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_QUOTA_EMPLOYEE ADD
    CONSTRAINT FK_QUOTA_EMPLOYEE_CLIENT FOREIGN KEY (CLIENT_ID)
    REFERENCES TBL_CLIENT (ID)
    ON DELETE RESTRICT;
	
	
-- PARTNERS CLIENTS
CREATE TABLE TBL_PARTNER_CLIENT (
	ID VARCHAR(50) NOT NULL COMMENT 'true',
	PARTNER_ID VARCHAR(50) NOT NULL COMMENT 'true',
	CLIENT_ID VARCHAR(50) NOT NULL COMMENT 'true',
	EMPLOYEE_ID VARCHAR(50) COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_PARTNER_CLIENT PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Contents the clients of a partner';
ALTER TABLE TBL_PARTNER_CLIENT ADD
    CONSTRAINT FK_PARTNER_CLIENT FOREIGN KEY (PARTNER_ID)
    REFERENCES TBL_PARTNER (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_PARTNER_CLIENT ADD
    CONSTRAINT FK_CLIENT_PARTNER_CLIENT FOREIGN KEY (CLIENT_ID)
    REFERENCES TBL_CLIENT (ID)
    ON DELETE RESTRICT;
	
-- AREA TYPES */
CREATE TABLE TBL_AREA_TYPE (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	PARENT_ID SMALLINT COMMENT 'true',
	AREA_TYPE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_AREA_TYPE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Area Types';

ALTER TABLE TBL_AREA ADD
    CONSTRAINT FK_AREA_AREA_TYPE FOREIGN KEY (AREA_TYPE_ID)
    REFERENCES TBL_AREA_TYPE (ID)
    ON DELETE RESTRICT;


-- SYSTEM COLORS
CREATE TABLE TBL_SYSTEM_COLOR (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	HEXA VARCHAR(10) NOT NULL COMMENT 'true',
	CLASS_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_SYSTEM_COLOR PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'System Color';
ALTER TABLE TBL_SYSTEM_COLOR ADD
    CONSTRAINT FK_SYSTEM_COLOR_RESOURCE FOREIGN KEY (RESOURCE_NAME)
    REFERENCES TBL_SYSTEM_RESOURCE (RESOURCE_NAME)
    ON DELETE RESTRICT;
	
	
--	USER ADDRESSES
CREATE TABLE TBL_USER_ADDRESSES (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	USER_ID VARCHAR(100) NOT NULL COMMENT 'true',
	ADDRESS_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	ADDRESS VARCHAR(200) NOT NULL COMMENT 'true',
	ZONE_ID INTEGER UNSIGNED NOT NULL COMMENT 'true',
	CITY_ID MEDIUMINT UNSIGNED COMMENT 'true',
	LATITUDE VARCHAR(100) COMMENT 'true',
	LONGITUDE VARCHAR(100) COMMENT 'true',
	IS_ORIGIN BOOLEAN DEFAULT FALSE COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT TBL_USER_ADDRESSES PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'User Addresses';
ALTER TABLE TBL_USER_ADDRESSES ADD
    CONSTRAINT FK_USER_ADDRESSES_USER FOREIGN KEY (USER_ID)
    REFERENCES TBL_SYSTEM_USER (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_USER_ADDRESSES ADD
	CONSTRAINT FK_USER_ADDRESSES_ZONE FOREIGN KEY (ZONE_ID)
    REFERENCES TBL_SYSTEM_ZONE (ID)
    ON DELETE RESTRICT;
	

-- SYSTEM ADDRESS TYPE
CREATE TABLE TBL_SYSTEM_ADDRESS_TYPE (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	NAME VARCHAR(100) NOT NULL COMMENT 'true',
	ABBREVIATION VARCHAR(10) COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT TBL_SYSTEM_ADDRESS_TYPE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'System address type';
	

-- PARTNER RATES
CREATE TABLE TBL_PARTNER_RATE (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	PARTNER_ID VARCHAR(50) NOT NULL COMMENT 'true',
	VEHICLE_TYPE_ID TINYINT UNSIGNED NOT NULL COMMENT 'true',
	DISTANCE_MIN FLOAT(18,3) NOT NULL DEFAULT 0 COMMENT 'true',
	DISTANCE_MAX FLOAT(18,3) NOT NULL DEFAULT 0 COMMENT 'true',
	TIME_MIN FLOAT(18,3) NOT NULL DEFAULT 0 COMMENT 'true',
	TIME_MAX FLOAT(18,3) NOT NULL DEFAULT 0 COMMENT 'true',
	PRICE FLOAT(18,3) NOT NULL DEFAULT 0 COMMENT 'true',
	ROUND_TRIP FLOAT(18,3) NOT NULL DEFAULT 0 COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(50) COMMENT 'true',
	CONSTRAINT PK_PARTNER_RATE PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = 'Partner Rates';
ALTER TABLE TBL_PARTNER_RATE ADD
    CONSTRAINT FK_PARTNER_RATE_PARTNER FOREIGN KEY (PARTNER_ID)
    REFERENCES TBL_PARTNER (ID)
    ON DELETE RESTRICT;
ALTER TABLE TBL_PARTNER_RATE ADD
	CONSTRAINT FK_PARTNER_RATE_VEHICLE_TYPE FOREIGN KEY (VEHICLE_TYPE_ID)
    REFERENCES TBL_SYSTEM_VEHICLE_TYPE (ID)
    ON DELETE RESTRICT;
