
-- Tabla Tarifas para clientes afilia tu empresa */
CREATE TABLE TBL_AFFILIATE_SUBSCRIPTION (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	-- RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	CLIENT_ID VARCHAR(50) NOT NULL COMMENT 'true',
	DETAILED_PLAN VARCHAR(50) NULL COMMENT 'true',
	AMOUNT FLOAT(18,3) NOT NULL DEFAULT '0.00' COMMENT 'true',
	START_DATE DATETIME NOT NULL COMMENT 'true',
	CREDIT_CARD_NUMBER VARCHAR(50) NOT NULL COMMENT 'true',
  	CREDIT_CARD_NAME VARCHAR(100) NOT NULL COMMENT 'true',
  	DATE_EXPIRATION VARCHAR(10) NOT NULL COMMENT 'true',
  	VERIFICATION_CODE VARCHAR(10) NOT NULL COMMENT 'true',
	CARD_STATUS VARCHAR(50) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_TBL_AFFILIATE_SUBSCRIPTION PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = "Contains the affiliate user's subscription";

ALTER TABLE TBL_AFFILIATE_SUBSCRIPTION ADD
    CONSTRAINT FK_TBL_AFFILIATE_SUBSCRIPTION_CLIENT_ID FOREIGN KEY (CLIENT_ID)
    REFERENCES TBL_CLIENT (ID)
    ON DELETE RESTRICT;

-- TRIGGER
DELIMITER //

CREATE TRIGGER TR_AFFILIATE_SUBSCRIPTION_B_INSERT BEFORE INSERT ON TBL_AFFILIATE_SUBSCRIPTION
FOR EACH ROW
BEGIN
    SET NEW.REGISTERED_ON = NOW();
END;
//

DELIMITER ;


DELIMITER //

CREATE TRIGGER TR_AFFILIATE_SUBSCRIPTION_B_UPDATE BEFORE UPDATE ON TBL_AFFILIATE_SUBSCRIPTION
FOR EACH ROW
BEGIN
    SET NEW.MODIFIED_ON = NOW();
END;
//

DELIMITER ;

-------------------------------------------------------*/