
-- Tabla Tarifas para clientes afilia tu empresa */
CREATE TABLE TBL_AFFILIATE_SUBSCRIPTION (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'true',
	-- RESOURCE_NAME VARCHAR(100) NOT NULL COMMENT 'true',
	CLIENT_ID VARCHAR(50) NOT NULL COMMENT 'true',
	DETAILED_PLAN VARCHAR(50) NULL COMMENT 'true',
	AMOUNT FLOAT(18,3) NOT NULL DEFAULT '0.00' COMMENT 'true',
	START_DATE DATETIME NOT NULL COMMENT 'true',
	CREDIT_CARD_NUMBER VARCHAR(50) NOT NULL COMMENT 'true',
  	CREDIT_CARD_NAME VARCHAR(100) NOT NULL COMMENT 'true',
  	DATE_EXPIRATION VARCHAR(10) NOT NULL COMMENT 'true',
  	VERIFICATION_CODE VARCHAR(10) NOT NULL COMMENT 'true',
	CARD_STATUS VARCHAR(50) NOT NULL COMMENT 'true',
	IS_BLOCKED BOOLEAN DEFAULT FALSE COMMENT 'true',
	REGISTERED_ON DATETIME NOT NULL COMMENT 'true',
	REGISTERED_BY VARCHAR(50) NOT NULL COMMENT 'true',
	MODIFIED_ON DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT 'true',
	MODIFIED_BY VARCHAR(100) COMMENT 'true',
	CONSTRAINT PK_TBL_AFFILIATE_SUBSCRIPTION PRIMARY KEY (ID)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_unicode_ci
COMMENT = "Contains the affiliate user's subscription";

ALTER TABLE TBL_AFFILIATE_SUBSCRIPTION ADD
    CONSTRAINT FK_TBL_AFFILIATE_SUBSCRIPTION_CLIENT_ID FOREIGN KEY (CLIENT_ID)
    REFERENCES TBL_CLIENT (ID)
    ON DELETE RESTRICT;

-- TRIGGER
DELIMITER //

CREATE TRIGGER TR_AFFILIATE_SUBSCRIPTION_B_INSERT BEFORE INSERT ON TBL_AFFILIATE_SUBSCRIPTION
FOR EACH ROW
BEGIN
    SET NEW.REGISTERED_ON = NOW();
END;
//

DELIMITER ;


DELIMITER //

CREATE TRIGGER TR_AFFILIATE_SUBSCRIPTION_B_UPDATE BEFORE UPDATE ON TBL_AFFILIATE_SUBSCRIPTION
FOR EACH ROW
BEGIN
    SET NEW.MODIFIED_ON = NOW();
END;
//

DELIMITER ;

-- -----------------------------------------------------*/

INSERT INTO TBL_SYSTEM_RESOURCE (RESOURCE_NAME,RESOURCE_TEXT,LANGUAGE_ID,IS_SYSTEM,IS_BLOCKED,REGISTERED_ON,REGISTERED_BY,MODIFIED_ON,MODIFIED_BY) VALUES
	 ('TBL_AFFILIATE_SUBSCRIPTION.CLIENT_ID','Cliente',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL),
	 ('TBL_AFFILIATE_SUBSCRIPTION.AMOUNT','number,Valor cupo,Valor cupo,,',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL),
	 ('TBL_AFFILIATE_SUBSCRIPTION.CREDIT_CARD_NUMBER','text,Tarjeta de crédito,Tarjeta de crédito,,',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL),
	 ('TBL_AFFILIATE_SUBSCRIPTION.CREDIT_CARD_NAME','text,Nombre tarjeta crédito,Nombre en tarjeta de crédito,change2Upper',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL),
	 ('TBL_AFFILIATE_SUBSCRIPTION.DATE_EXPIRATION','text,Fecha vencimiento (MM/YY),Fecha vencimiento (MM/YY),,',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL),
	 ('TBL_AFFILIATE_SUBSCRIPTION.VERIFICATION_CODE','text,Código verificación,Código verificación,,',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL);
INSERT INTO TBL_SYSTEM_RESOURCE (RESOURCE_NAME,RESOURCE_TEXT,LANGUAGE_ID,IS_SYSTEM,IS_BLOCKED,REGISTERED_ON,REGISTERED_BY,MODIFIED_ON,MODIFIED_BY) VALUES
	 ('TBL_AFFILIATE_SUBSCRIPTION.CARD_STATUS','text,Estado,Estado,,',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL),
	 ('TBL_AFFILIATE_SUBSCRIPTION.IS_BLOCKED','¿Bloqueado?',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL),
	 ('TBL_AFFILIATE_SUBSCRIPTION.REGISTERED_BY','text,Registrado por,Registrado por,,',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL),
	 ('TBL_AFFILIATE_SUBSCRIPTION.REGISTERED_ON','text,Registrado en,Registrado en,,',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL),
	 ('TBL_AFFILIATE_SUBSCRIPTION.MODIFIED_BY','text,Modificado por,Modificado por,,',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL);
INSERT INTO TBL_SYSTEM_RESOURCE (RESOURCE_NAME,RESOURCE_TEXT,LANGUAGE_ID,IS_SYSTEM,IS_BLOCKED,REGISTERED_ON,REGISTERED_BY,MODIFIED_ON,MODIFIED_BY) VALUES
	 ('TBL_AFFILIATE_SUBSCRIPTION.MODIFIED_ON','text,Modificado en,Modificado en,,',2,0,0,'2022-12-19 16:25:19','carlcaba',NULL,NULL);


-- Nuevo campos en la tabla cliente Representante legal
ALTER TABLE `TBL_CLIENT` DROP FOREIGN KEY `FK_CLIENT_CITY`;
ALTER TABLE `TBL_CLIENT` DROP FOREIGN KEY `FK_CLIENT_CLIENT_PAYMENT_TYPE_`;
ALTER TABLE `TBL_CLIENT` DROP FOREIGN KEY `FK_CLIENT_PAYMENT_TYPE`;
ALTER TABLE `TBL_PARTNER_CLIENT` DROP FOREIGN KEY `FK_CLIENT_PARTNER_CLIENT`;
ALTER TABLE `TBL_CLIENT` ENGINE = MyISAM;

ALTER TABLE `TBL_CLIENT` ADD `LEGAL_REPRESENTATIVE` VARCHAR(200) COLLATE utf8_unicode_ci NULL COMMENT 'true';

ALTER TABLE `TBL_CLIENT` ADD CONSTRAINT `FK_CLIENT_CITY` FOREIGN KEY (`CITY_ID`) REFERENCES `TBL_SYSTEM_CITY` (`ID`);
ALTER TABLE `TBL_CLIENT` ADD CONSTRAINT `FK_CLIENT_CLIENT_PAYMENT_TYPE_` FOREIGN KEY (`CLIENT_PAYMENT_TYPE_ID`) REFERENCES `TBL_SYSTEM_CLIENT_PAYMENT_TYPE` (`ID`);
ALTER TABLE `TBL_CLIENT` ADD CONSTRAINT `FK_CLIENT_PAYMENT_TYPE` FOREIGN KEY (`PAYMENT_TYPE_ID`) REFERENCES `TBL_SYSTEM_PAYMENT_TYPE` (`ID`);
ALTER TABLE `TBL_PARTNER_CLIENT` ADD CONSTRAINT `FK_CLIENT_PARTNER_CLIENT` FOREIGN KEY (`CLIENT_ID`) REFERENCES `TBL_CLIENT` (`ID`),

ALTER TABLE `TBL_CLIENT` ENGINE = INNODB;


INSERT INTO TBL_SYSTEM_RESOURCE
(RESOURCE_NAME, RESOURCE_TEXT, LANGUAGE_ID, IS_SYSTEM, IS_BLOCKED, REGISTERED_ON, REGISTERED_BY, MODIFIED_ON, MODIFIED_BY)
VALUES('TBL_CLIENT.LEGAL_REPRESENTATIVE', 'text,Representante Legal,Nombre Representante Legal,change2Upper', 2, 0, 0, '2022-12-19 14:24:24', 'carlcaba', NULL, NULL);